# opt-env-conf 0.13.0.0 from Hackage
#
# Why we need this:
# nixpkgs only has opt-env-conf 0.9.0.0, but we need 0.13.0.0.
# The nixpkgs Haskell package set is a periodic snapshot from Hackage
# (generated by hackage2nix), so it often lags behind the latest versions.
# We use cabal2nix to generate this file directly from Hackage.
#
# To regenerate:
#   nix-shell -p cabal2nix cabal-install --run "cabal update && cabal2nix cabal://opt-env-conf-0.13.0.0"
#
{
  mkDerivation,
  aeson,
  autodocodec,
  autodocodec-nix,
  autodocodec-schema,
  autodocodec-yaml,
  base,
  containers,
  hashable,
  lib,
  mtl,
  path,
  path-io,
  safe-coloured-text,
  safe-coloured-text-layout,
  safe-coloured-text-terminfo,
  selective,
  text,
  validity,
  validity-containers,
  validity-text,
}:
mkDerivation {
  pname = "opt-env-conf";
  version = "0.13.0.0";
  sha256 = "8a68de27b51536e86531ae3deeb6dc595b883dd42d54d6df2dc845f0072cef68";
  libraryHaskellDepends = [
    aeson
    autodocodec
    autodocodec-nix
    autodocodec-schema
    autodocodec-yaml
    base
    containers
    hashable
    mtl
    path
    path-io
    safe-coloured-text
    safe-coloured-text-layout
    safe-coloured-text-terminfo
    selective
    text
    validity
    validity-containers
    validity-text
  ];
  homepage = "https://github.com/NorfairKing/opt-env-conf#readme";
  description = "Settings parsing for Haskell: command-line arguments, environment variables, and configuration values";
  license = lib.licenses.lgpl3Only;
}
